spring:
  application:
    name: awesomepizza
  datasource:
    url: jdbc:postgresql://localhost:5433/awesomepizza_db
    username: awesomepizza_user
    password: awesomepizza_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true