spring:
  application:
    name: awesomepizza
  datasource:
    url: jdbc:postgresql://localhost:5433/awesomepizza_db
    username: awesomepizza_user
    password: awesomepizza_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  security:
    pizzaiolo:
      username: pizzaiolo
      password: password

logging:
  level:
    com.awesomepizza: INFO
    org.springframework: WARN
    org.hibernate: WARN